export default [
	{
		key: 10,
		title: 'memory game',
		lenguages: 'react',
		date: '6 Feb, 2025',
		description: 'Memory game created as a final project for a React course.',
		imageUrl: 'https://imgur.com/aguu2lp.jpg',
		siteUrl: 'https://memorygameclaudio.netlify.app/',
	},
	{
		key: 9,
		title: 'assembly endgame',
		lenguages: 'react',
		date: '27 Gen, 2025',
		description: 'Final big task of a intermediate course about React JS.',
		imageUrl: 'https://imgur.com/ktYfez7.jpg',
		siteUrl: 'https://assemblyendgameclaudio.netlify.app/',
	},
	{
		key: 8,
		title: 'movies watchlist',
		lenguages: 'html-tailwind-javascript-APIs',
		date: '08 Oct, 2024',
		description: 'First page using TailwindCSS where I also utilized APIs.',
		imageUrl: 'https://imgur.com/Wqaj2Dg.jpg',
		siteUrl: 'https://moviewatchlistclaudio.netlify.app/',
	},
	{
		key: 7,
		title: 'color scheme generator',
		lenguages: 'html-css-javascript-API',
		date: '24 Sep, 2024',
		description: 'Color palette generator using an API.',
		imageUrl: 'https://imgur.com/2hJaa5P.jpg',
		siteUrl: 'https://colorschemegeneratorclaudio.netlify.app/',
	},
	{
		key: 6,
		title: 'twimba social',
		lenguages: 'html-css-javascript-uuid',
		date: '28 Aug, 2024',
		description:
			'Twitter clone created as a course assignment, with several additional features added.',
		imageUrl: 'https://imgur.com/lUaTjnB.jpg',
		siteUrl: 'https://twimbaclaudio.netlify.app/',
	},
	{
		key: 5,
		title: 'quizzical game',
		lenguages: 'html-css-javascript-react',
		date: '25 Jul, 2024',
		description: 'Quiz made with React that also uses an API for the questions.',
		imageUrl: 'https://imgur.com/omodrya.jpg',
		siteUrl: 'https://quizzicalclaudio.netlify.app/',
	},
	{
		key: 4,
		title: 'tenzie game',
		lenguages: 'html-css-javascript-react',
		date: '21 Jul, 2024',
		description: 'A very simple game where I applied my latest learnings in React.',
		imageUrl: 'https://imgur.com/FodhjYd.jpg',
		siteUrl: 'https://tenzieclaudio.netlify.app/',
	},
	{
		key: 3,
		title: 'shopping app',
		lenguages: 'html-css-javascript-firebase',
		date: '4 Jun, 2024',
		description: 'Mobile app that allows you to share your shopping list in real-time with others.',
		imageUrl: 'https://i.imgur.com/g4M5QrD.jpg',
		siteUrl: 'https://shoppingclaudiodemo.netlify.app/',
	},
	{
		key: 2,
		title: 'personal page Tania Mirasol',
		lenguages: 'html-css-javascript',
		date: '30 Apr, 2024',
		description:
			'Main website for a personal brand, currently developing an improved version that also includes React.',
		imageUrl: 'https://i.imgur.com/oZsl9qm.jpg',
		siteUrl: 'https://taniamirasolanton.netlify.app/',
	},
	{
		key: 1,
		title: 'calculator',
		lenguages: 'html-css-javascript',
		date: '16 Apr, 2024',
		description:
			'Calculator created as an assignment for my higher education degree, focusing not only on functionality but also on design.',
		imageUrl: 'https://i.imgur.com/s2qRUQN.jpg',
		siteUrl: 'https://claudiocalculadora.netlify.app/',
	},
]
